### ISSUE TITLE
Potential diff bug

### ISSUE THREAD

**Issue by corwinstephen** [w8tcha/CKEditor-AutoSave-Plugin#27] opened 2014-06-13 18:49 UTC
Have CKEditor set up in a Rails app with almost no customization at all. When autosave runs, I get the alert asking me if I want to diff, and then it throws this exception:

Uncaught TypeError: Cannot read property '0' of undefined extensions.min.js?t=E4KA:1
get_matching_blocks extensions.min.js?t=E4KA:1
get_opcodes extensions.min.js?t=E4KA:1
RenderDiff plugin.js?t=E4KA:240
onShow plugin.js?t=E4KA:111
i ckeditor.js?body=1:11
CKEDITOR.event.CKEDITOR.event.fire ckeditor.js?body=1:13
(anonymous function) ckeditor.js?body=1:535
(anonymous function) ckeditor.js?body=1:26
wrapped

Accepting changes still works, but the diff never shows up.

Verified in Chrome, Safari, Firefox, Opera

![screen shot 2014-06-13 at 11 49 03 am](https://cloud.githubusercontent.com/assets/1714875/3274111/71302288-f32b-11e3-917e-e5a2c53d4fbf.png)

**Comment by julienkrs** [comment] 2015-06-23 08:44
I can second the bug, occurs for us when clicking on "side by side view" (or when the popup loads, in which case side by side is selected anyway).
Using CKEditor 4.4.7, but an older jQuery version (1.8.x). No other options that the standard config.

Here is the error that is displayed:
Argument 1 of Node.appendChild does not implement interface Node

**Comment by zassq** [comment] 2015-08-12 02:51
Same problem as julienkrs, same error message.
Using CKEditor 4.5.2

Besides, is there any possible to add a config to turn-on/off this diff thing?
I prefer to auto restore if saved data found.

Thank you so much!

**Comment by master-bob** [comment] 2016-08-17 15:27
I see a similar error as well:
Chromium:
```
extensions.min.js?t=G14E:1 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.buildView @ extensions.min.js?t=G14E:1RenderDiff @ plugin.js?t=G14E:236onShow @ plugin.js?t=G14E:111dialogDefinition.onShow @ ckeditor.launch.js?version=:235n @ ckeditor.js?version=:10CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js?version=:12(anonymous function) @ ckeditor.js?version=:568(anonymous function) @ ckeditor.js?version=:28
```

Firefox:
```
TypeError: Argument 1 of Node.appendChild does not implement interface Node.
	

...reateElement("tbody"));for(var t in m){y.appendChild(m[t])}y=E("table","diff"+(d...

	
extensi...?t=G14E (line 1, col 7667)
```

This is on whatever version of CKEditor Sakai 11.0 ships with, https://jira.sakaiproject.org/browse/SAK-31113 .

**Comment by jonespm** [comment] 2016-12-01 01:45
@w8tcha The version of difflib on https://github.com/cemerick/jsdifflib works after recompling the extensions. Just replace difflib.js and diffview.js with the files that are there. I pushed the changes to those two files there.

![image](https://cloud.githubusercontent.com/assets/27447/20778751/2b7722aa-b72d-11e6-96e9-2000a86b6645.png)


https://github.com/w8tcha/CKEditor-AutoSave-Plugin/compare/master...jonespm:diffview-27

**Comment by w8tcha** [comment] 2016-12-10 13:11
The problem is that this version doesn't work it not show the changes correctly.

**Comment by jonespm** [comment] 2016-12-22 23:28
@w8tcha Well if you don't want the whole library I believe the specific fix for this item was 

https://github.com/cemerick/jsdifflib/commit/76123ecff2530f432b6341083520eee27aff8695

Though in my testing that version is working better than this one.

**Comment by w8tcha** [comment] 2016-12-24 12:58
Okay i applied the changes, hopefully that fixes the problem!

**Closed** 2017-06-25 09:34 UTC
